version: "3"

services:
  app:
    container_name: app
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8082:8082"
    expose:
      - "8082"
